import type { ActionsOperations } from "./actions.js";
import type { ActivityOperations } from "./activity.js";
import type { AgentTasksOperations } from "./agentTasks.js";
import type { AgentsOperations } from "./agents.js";
import type { ApiInsightsOperations } from "./apiInsights.js";
import type { AppsOperations } from "./apps.js";
import type { BillingOperations } from "./billing.js";
import type { CampaignsOperations } from "./campaigns.js";
import type { ChecksOperations } from "./checks.js";
import type { ClassroomOperations } from "./classroom.js";
import type { CodeQualityOperations } from "./codeQuality.js";
import type { CodeScanningOperations } from "./codeScanning.js";
import type { CodeSecurityOperations } from "./codeSecurity.js";
import type { CodesOfConductOperations } from "./codesOfConduct.js";
import type { CodespacesOperations } from "./codespaces.js";
import type { CopilotOperations } from "./copilot.js";
import type { CopilotSpacesOperations } from "./copilotSpaces.js";
import type { CredentialsOperations } from "./credentials.js";
import type { DependabotOperations } from "./dependabot.js";
import type { DependencyGraphOperations } from "./dependencyGraph.js";
import type { EmojisOperations } from "./emojis.js";
import type { EnterpriseTeamMembershipsOperations } from "./enterpriseTeamMemberships.js";
import type { EnterpriseTeamOrganizationsOperations } from "./enterpriseTeamOrganizations.js";
import type { EnterpriseTeamsOperations } from "./enterpriseTeams.js";
import type { GistsOperations } from "./gists.js";
import type { GitOperations } from "./git.js";
import type { GitignoreOperations } from "./gitignore.js";
import type { HostedComputeOperations } from "./hostedCompute.js";
import type { InteractionsOperations } from "./interactions.js";
import type { IssuesOperations } from "./issues.js";
import type { LicensesOperations } from "./licenses.js";
import type { MarkdownOperations } from "./markdown.js";
import type { MetaOperations } from "./meta.js";
import type { MigrationsOperations } from "./migrations.js";
import type { OidcOperations } from "./oidc.js";
import type { OrgsOperations } from "./orgs.js";
import type { PackagesOperations } from "./packages.js";
import type { PrivateRegistriesOperations } from "./privateRegistries.js";
import type { ProjectsOperations } from "./projects.js";
import type { PullsOperations } from "./pulls.js";
import type { RateLimitOperations } from "./rateLimit.js";
import type { ReactionsOperations } from "./reactions.js";
import type { ReposOperations } from "./repos.js";
import type { SearchOperations } from "./search.js";
import type { SecretScanningOperations } from "./secretScanning.js";
import type { SecurityAdvisoriesOperations } from "./securityAdvisories.js";
import type { TeamsOperations } from "./teams.js";
import type { UsersOperations } from "./users.js";

export type GithubClient = {
  actions: ActionsOperations;
  activity: ActivityOperations;
  agentTasks: AgentTasksOperations;
  agents: AgentsOperations;
  apiInsights: ApiInsightsOperations;
  apps: AppsOperations;
  billing: BillingOperations;
  campaigns: CampaignsOperations;
  checks: ChecksOperations;
  classroom: ClassroomOperations;
  codeQuality: CodeQualityOperations;
  codeScanning: CodeScanningOperations;
  codeSecurity: CodeSecurityOperations;
  codesOfConduct: CodesOfConductOperations;
  codespaces: CodespacesOperations;
  copilot: CopilotOperations;
  copilotSpaces: CopilotSpacesOperations;
  credentials: CredentialsOperations;
  dependabot: DependabotOperations;
  dependencyGraph: DependencyGraphOperations;
  emojis: EmojisOperations;
  enterpriseTeamMemberships: EnterpriseTeamMembershipsOperations;
  enterpriseTeamOrganizations: EnterpriseTeamOrganizationsOperations;
  enterpriseTeams: EnterpriseTeamsOperations;
  gists: GistsOperations;
  git: GitOperations;
  gitignore: GitignoreOperations;
  hostedCompute: HostedComputeOperations;
  interactions: InteractionsOperations;
  issues: IssuesOperations;
  licenses: LicensesOperations;
  markdown: MarkdownOperations;
  meta: MetaOperations;
  migrations: MigrationsOperations;
  oidc: OidcOperations;
  orgs: OrgsOperations;
  packages: PackagesOperations;
  privateRegistries: PrivateRegistriesOperations;
  projects: ProjectsOperations;
  pulls: PullsOperations;
  rateLimit: RateLimitOperations;
  reactions: ReactionsOperations;
  repos: ReposOperations;
  search: SearchOperations;
  secretScanning: SecretScanningOperations;
  securityAdvisories: SecurityAdvisoriesOperations;
  teams: TeamsOperations;
  users: UsersOperations;
};

export * from "./actions.js";
export * from "./activity.js";
export * from "./agentTasks.js";
export * from "./agents.js";
export * from "./apiInsights.js";
export * from "./apps.js";
export * from "./billing.js";
export * from "./campaigns.js";
export * from "./checks.js";
export * from "./classroom.js";
export * from "./codeQuality.js";
export * from "./codeScanning.js";
export * from "./codeSecurity.js";
export * from "./codesOfConduct.js";
export * from "./codespaces.js";
export * from "./copilot.js";
export * from "./copilotSpaces.js";
export * from "./credentials.js";
export * from "./dependabot.js";
export * from "./dependencyGraph.js";
export * from "./emojis.js";
export * from "./enterpriseTeamMemberships.js";
export * from "./enterpriseTeamOrganizations.js";
export * from "./enterpriseTeams.js";
export * from "./gists.js";
export * from "./git.js";
export * from "./gitignore.js";
export * from "./hostedCompute.js";
export * from "./interactions.js";
export * from "./issues.js";
export * from "./licenses.js";
export * from "./markdown.js";
export * from "./meta.js";
export * from "./migrations.js";
export * from "./oidc.js";
export * from "./orgs.js";
export * from "./packages.js";
export * from "./privateRegistries.js";
export * from "./projects.js";
export * from "./pulls.js";
export * from "./rateLimit.js";
export * from "./reactions.js";
export * from "./repos.js";
export * from "./search.js";
export * from "./secretScanning.js";
export * from "./securityAdvisories.js";
export * from "./teams.js";
export * from "./users.js";
export * from "./schemas.js";
