/**
 * Generate the credential scaffold from the provider matrix.
 *
 * Writing this by hand would guarantee drift: add a provider, forget its env
 * var, and the suite skips forever. Generating it means the scaffold is always
 * exactly the set of variables the flows actually read.
 *
 *   pnpm --filter @utdk/e2e env:scaffold            # writes .env.example
 *   pnpm --filter @utdk/e2e env:scaffold -- --env   # also writes .env if absent
 */

import { writeFileSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { credentialEnvKeys } from "../src/env.js";
import { PROVIDERS } from "../src/matrix.js";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");

const SIGNUP_LABEL: Record<string, string> = {
  "self-serve": "free signup",
  "self-serve-limited": "signup, limited free tier",
  paid: "paid plan required",
  "invite-only": "no self-serve signup",
  "not-applicable": "no account needed",
};

function render(): string {
  const lines: string[] = [
    "# UTDK provider E2E credentials",
    "#",
    "# Generated by `pnpm --filter @utdk/e2e env:scaffold` — do not hand-maintain the",
    "# variable list; regenerate it when the provider matrix changes.",
    "#",
    "# Every variable is optional. A provider whose variables are blank is SKIPPED,",
    "# never failed, so a partially-filled file is a valid state. Fill in the",
    "# providers you care about and re-run `pnpm --filter @utdk/e2e test:live`.",
    "#",
    "# Check readiness at any time with: pnpm --filter @utdk/e2e doctor",
    "",
    "# ---------------------------------------------------------------------------",
    "# Gateway target (flows 3 and 4). Without this, only the direct-SDK flow runs.",
    "#",
    "# The gateway API is mounted under /api/gateway — only /health sits at the root,",
    "# so a bare origin 404s on every endpoint. Local default port is 4000:",
    "#   UTDK_E2E_GATEWAY_URL=http://localhost:4000/api/gateway",
    "#",
    "# Deployed: set the token to a Cognito access token for the workspace.",
    "# ---------------------------------------------------------------------------",
    "UTDK_E2E_GATEWAY_URL=",
    "UTDK_E2E_GATEWAY_TOKEN=",
    "",
  ];

  const sorted = [...PROVIDERS].sort((a, b) => a.id.localeCompare(b.id));
  const seen = new Set<string>();

  for (const entry of sorted) {
    const credentialKeys = credentialEnvKeys(entry.auth);
    const fixtureKeys = [
      ...(entry.probe?.needs ?? []),
      ...(entry.probe?.baseUrlEnv ? [entry.probe.baseUrlEnv] : []),
    ];
    const keys = [...credentialKeys, ...fixtureKeys].filter((key) => !seen.has(key));

    if (keys.length === 0) continue;
    for (const key of keys) seen.add(key);

    lines.push(
      "# ---------------------------------------------------------------------------",
      `# ${entry.label} (${entry.id})${entry.signup ? ` — ${SIGNUP_LABEL[entry.signup] ?? entry.signup}` : ""}`,
    );
    if (entry.credentialUrl) lines.push(`# Obtain: ${entry.credentialUrl}`);
    if (entry.credentialHint) lines.push(`# ${entry.credentialHint}`);
    if (entry.unprobed) lines.push(`# NOTE: no live probe yet — ${entry.unprobed.replace(/\s+/g, " ")}`);
    lines.push("# ---------------------------------------------------------------------------");
    for (const key of keys) lines.push(`${key}=`);
    lines.push("");
  }

  return lines.join("\n");
}

const content = render();
const examplePath = join(packageRoot, ".env.example");
writeFileSync(examplePath, content, "utf8");
console.log(`wrote ${examplePath}`);

if (process.argv.includes("--env")) {
  const envPath = join(packageRoot, ".env");
  if (existsSync(envPath)) {
    console.log(`skipped ${envPath} — already exists (refusing to overwrite credentials)`);
  } else {
    writeFileSync(envPath, content, "utf8");
    console.log(`wrote ${envPath}`);
  }
}
