/**
 * Generated app SDK — the manifest is the world, this is the bindings.
 *
 * A widget's namespaces are injected as globals today (`window.vfs`), which is
 * untyped and invisible to an editor. The contract an app author writes
 * against is instead an importable module with generated types:
 *
 *   import vfs from "vfs";
 *   import app from "app";                      // this app's exported workflows
 *   const out = await app.weeklySummary({ weeks: 4 });   // typed in and out
 *
 * Two artefacts, both derived from the manifest plus each exported workflow's
 * declared JSON Schemas:
 *
 *   - `js`  — a runtime shim over the SAME app tool proxy the compiler already
 *             uses (`window.__APP_CONFIG__.appBase + "/tools"`), so an import
 *             and a global are two spellings of one call path. Owned here: the
 *             transport, the auth headers and the proxy convention are the
 *             gateway's business.
 *   - `dts` — types, generated by `@aprovan/patchwork-compiler/namespace-types`,
 *             the SAME function the editor and the playground call. There was
 *             a second copy of this generator here; two implementations of one
 *             contract drift, and the whole promise of the SDK is that a widget
 *             sees identical types in chat, in the playground and on the live
 *             page. The compiler's version is now the only one.
 *
 * What the gateway still contributes to the types, because only it knows:
 * which native procedures this app's `allowedTools` actually permit, and where
 * each namespace's data physically lands.
 *
 * JSON Schema → TS handles the $ref-free basics (object/array/string/number/
 * boolean/null/enum/anyOf/oneOf/allOf) and falls back to `unknown`, which is
 * exactly the "undeclared = unknown, and the call still works" rule.
 */

import {
  generateNamespaceTypes,
  type JsonSchema,
} from "@aprovan/patchwork-compiler/namespace-types";

import { nativeCapabilities } from "./capabilities.js";
import type { AppManifest } from "./store.js";

export interface AppSdkWorkflow {
  name: string;
  description?: string;
  input?: Record<string, unknown>;
  output?: Record<string, unknown>;
}

export interface GeneratedSdk {
  js: string;
  dts: string;
  /** Namespaces the shim exports (native allow-listed + "app"). */
  namespaces: string[];
}

/** The runtime shim + its types for one app (optionally pinned to a channel). */
export function generateAppSdk(
  manifest: AppManifest,
  workflows: AppSdkWorkflow[],
  options: { channel?: string } = {},
): GeneratedSdk {
  const native = nativeCapabilities(manifest);
  const namespaces = [...native.map((capability) => capability.namespace), "app"];
  const header =
    `// Generated for app "${manifest.name}"` +
    (options.channel ? ` (channel: ${options.channel})` : "") +
    ` — do not edit.\n// Every call rides the app tool proxy: POST <appBase>/tools/<namespace>/<procedure>\n`;

  // -- js ------------------------------------------------------------------
  const js = `${header}
const config = (typeof window !== "undefined" && window.__APP_CONFIG__) || {};
const base = String(config.appBase || "").replace(/\\/$/, "") + "/tools";

async function call(namespace, procedure, args) {
  const response = await fetch(base + "/" + namespace + "/" + procedure, {
    method: "POST",
    headers: Object.assign({ "Content-Type": "application/json" }, config.authHeaders || {}),
    body: JSON.stringify({ args: args === undefined ? {} : args }),
  });
  let body = {};
  try {
    body = await response.json();
  } catch {
    body = {};
  }
  if (!response.ok) {
    throw new Error(body && body.error ? body.error : namespace + "." + procedure + " failed (" + response.status + ")");
  }
  return body && "data" in body ? body.data : body;
}

// Property access builds a dotted procedure path (github.repos.get), the same
// convention the workflow sandbox and the widget bridge use; calling it
// dispatches. \`then\` is masked so an accidental \`await ns\` can't look thenable.
function namespaceProxy(namespace, path) {
  return new Proxy(function () {}, {
    get(_target, property) {
      if (typeof property !== "string" || property === "then") return undefined;
      return namespaceProxy(namespace, path ? path + "." + property : property);
    },
    apply(_target, _thisArg, args) {
      return call(namespace, path || "default", args[0]);
    },
  });
}

${namespaces.map((namespace) => `export const ${namespace} = namespaceProxy(${JSON.stringify(namespace)}, "");`).join("\n")}

export { call as invoke, namespaceProxy };

export default { ${namespaces.join(", ")} };
`;

  // -- dts -----------------------------------------------------------------
  //
  // Ambient `declare module` blocks, one per namespace: that is what makes
  // `import vfs from "vfs"` resolve in an editor, and it is the same file the
  // compiler hands the playground. The two things the compiler cannot know are
  // passed in — the allow-list-filtered procedure set, and where the data lands.
  const procedures: Record<string, string[]> = {};
  const notes: Record<string, string> = {};
  for (const capability of native) {
    procedures[capability.namespace] = capability.procedures;
    notes[capability.namespace] =
      `${capability.description}\n` +
      `Data: ${capability.partitioning.path} (${capability.partitioning.mode}).\n` +
      capability.partitioning.description;
  }

  const dts =
    header +
    "\n" +
    generateNamespaceTypes(
      namespaces,
      workflows.map((workflow) => ({
        name: workflow.name,
        description: workflow.description,
        input: workflow.input as JsonSchema | undefined,
        output: workflow.output as JsonSchema | undefined,
      })),
      { procedures, notes },
    );

  return { js, dts, namespaces };
}
